[phases.setup]
nixPkgs = ["bun"]  # Esto asegura que Bun esté disponible

[phases.install]
cmds = ["bun install"]  # Instala las dependencias usando Bun

[phases.build]
cmds = ["bun run build"]  # Construye la aplicación para producción

[start]
cmd = "bun start"  # Comando para iniciar la aplicación
