name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies with Bun
        run: bun install

      - name: Build project
        run: bun run build

      - name: Build Docker image
        run: docker build -t zeppelin-frontend:latest .

      - name: Stop and remove previous container
        run: |
          docker stop zeppelin-frontend || true
          docker rm zeppelin-frontend || true

      - name: Run Docker container
        run: docker run -d --name zeppelin-frontend -p 3002:3002 zeppelin-frontend:latest
