name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Clonar o actualizar el código en el directorio correcto
      - name: Clonar o actualizar el código
        run: |
          if [ ! -d "/home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend" ]; then
            git clone https://github.com/${{ github.repository }}.git /home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend
          else
            cd /home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend
            git pull origin main
          fi

      # 2️⃣ Instalar dependencias con Bun
      - name: Install dependencies with Bun
        run: |
          cd /home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend
          bun install

      # 3️⃣ Construir el proyecto
      - name: Build project
        run: |
          cd /home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend
          bun run build

      # 4️⃣ Construir la imagen Docker (sin root)
      - name: Build Docker image
        run: |
          cd /home/runner/zeppelin/gh-runners/frontend-runner/zeppelin-frontend
          docker build -t zeppelin-frontend:latest .

      # 5️⃣ Detener y eliminar el contenedor anterior (sin root)
      - name: Stop and remove previous container
        run: |
          docker stop zeppelin-frontend || true
          docker rm zeppelin-frontend || true

      # 6️⃣ Correr el nuevo contenedor (sin root)
      - name: Run Docker container
        run: |
          docker run -d --name zeppelin-frontend -p 3002:3002 zeppelin-frontend:latest
